### PR TITLE
[FEATURE] Change showinpreview to preview mode

### PR DESCRIPTION
**Pull request by t3easy**
To allow to show a media only in preview/list the bool showinpreview was changed to a integer mode select.
It's extendable from outside to easy implement a new view mode, e.g. `show on home page` by adding a values to the TCA, extending the news class and add own getter and/or override existing ones.
Resolves: #218

### CODE REVIEW

**Comment by georgringer** [comment]
would be great if you could take a look at the conflict. I will try to review + merge shortly after that then

**Comment by r4fx** [comment]
Love to see it in next release

**Comment by t3easy** [comment]
Hi @georgringer should I take a look at this feature afresh?

**Comment by t3easy** [comment]
@r4fx Would you review, test and give feedback?

**Comment by georgringer** [comment]
now pushed with some different code, thx for big inspiration

**Pull request closed without merging**
