### PR TITLE
[BUGFIX] Use FlexFormTools to clean up flexforms in plugin updater

### PR DESCRIPTION
**Pull request by eliashaeussler**
By using the `FlexFormTools->cleanFlexFormXML()` method, registered hooks for flexform modifications are also taken into account. Without its usage, those additional fields would get removed during an upgrade.

Resolves: #2172

### CODE REVIEW

**Comment by liayn** [comment]
I justed tested dev-main again, but unfortunately this now leads to:
`PHP Warning: Undefined global variable $LANG in /var/www/html/vendor/typo3/cms-form/Classes/Hooks/DataStructureIdentifierHook.php line 403`

So we have a hook in Core, that assumes `$GLOBALS['LANG']` is present.
What shall we do? Init $LANG? Fix Core?

**Comment by DavidBruchmann** [comment]
It's very unlikely that `$GLOBALS['LANG']` will be re-introduced in the core.

**Comment by liayn** [comment]
> It's very unlikely that `$GLOBALS['LANG']` will be re-introduced in the core.

Not sure what you mean? I'm testing on v11 here, so Core is **using** it by itself.
The fix in v11 Core would be to not rely on the global an fallback to creating a dedicated instance of the `LanguageService`.

Besides that: The fix does not work with eventnews v6 currently. I'm still investigating this.

**Comment by liayn** [comment]
Note: 

> What shall we do? Init $LANG? Fix Core?

Initializing `$GLOBALS['LANG']` in the PluginUpdater helps to mitigate the problem in v11 at least.

> Besides that: The fix does not work with eventnews v6 currently. I'm still investigating this.

Something is wrong with the generated DS somehow.

**Comment by DavidBruchmann** [comment]
anyway, it's then an issue for the form extension and not directly related to news.

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Deprecation-88567-GLOBALS_LOCAL_LANG.html?highlight=globals%20lang

**Comment by liayn** [comment]
> anyway, it's then an issue for the form extension and not directly related to news.
> 
> https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Deprecation-88567-GLOBALS_LOCAL_LANG.html?highlight=globals%20lang

` $GLOBALS['LOCAL_LANG']`  vs. ` $GLOBALS['LANG']` :-)

It is an issue of news here too, because it is using the Flexform stuff outside the expected context. The ext-form hook never expected to be called in an install-tool-context.
So, I'd say we have to cope with this in news.

**Comment by DavidBruchmann** [comment]
concerning the DS Elias provided just a PR which is already merged I think, not sure if this could be related

**Comment by DavidBruchmann** [comment]
ahh this change :/

**Comment by liayn** [comment]
The ext:form issue is solved with: https://github.com/georgringer/news/pull/2197

**Comment by IchHabRecht** [comment]
For me the creation of LanguageService failed in a current TYPO3 12.4 installation. I added another pull request: https://github.com/georgringer/news/pull/2199

**Pull request merged**
